clc
clear
close all

MIN_BOUND = 65;
MAX_BOUND = 120;

a = uicontrol();
b = uicontrol();
c = uicontrol();

% Init serial connection
arduino = serialport(serialportlist, 115200);

f = figure;
subplot(1,2,1);

% A Control
a = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,50,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'A');
addlistener(a, 'Value', 'PostSet', @(~, x) update(arduino, ...
                                                  x.AffectedObject, ...
                                                  [a, b, c]));

al1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,50,23,23],...
                           'String', a.Min);
al2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,50,23,23],...
                           'String', a.Max);
al3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,25,100,23],...
                           'String', a.String);

% B Control
b = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,200,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'B');
addlistener(b, 'Value', 'PostSet', @(~, x) update(arduino, ...
                                                  x.AffectedObject, ...
                                                  [a, b, c]));

bl1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,200,23,23],...
                           'String', b.Min);
bl2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,200,23,23],...
                           'String', b.Max);
bl3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,175,100,23],...
                           'String', b.String);

% C Control
c = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,350,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'C');
addlistener(c, 'Value', 'PostSet', @(~, x) update(arduino, ...
                                                  x.AffectedObject, ...
                                                  [a, b, c]));

cl1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,350,23,23],...
                           'String', c.Min);
cl2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,350,23,23],...
                           'String', c.Max);
cl3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,325,100,23],...
                           'String', c.String);


function [] = update(arduino, control, handles)

  a = handles(1);
  b = handles(2);
  c = handles(3);

  % Write data to robot
  writeline(arduino, sprintf('%s%d', control.String, round(control.Value)));
  
  % Update simulation
  l1 = 70;
  l2 = 85;
  L = 85;
  
  Lpa = L - l1*cosd(a.Value);
  Lpb = L - l1*cosd(b.Value);
  Lpc = L - l1*cosd(c.Value);
  
  Ja = [0, Lpa, l1*sind(a.Value)];
  Jb = [ sqrt(3)/2*Lpb, -1/2*Lpb, l1*sind(b.Value)];
  Jc = [-sqrt(3)/2*Lpc, -1/2*Lpc, l1*sind(c.Value)];
  
  vAB = Jb - Ja;
  vAC = Jc - Ja;
  n = cross(vAB, vAC);
  n = n/norm(n);
  line(n(1), n(2), n(3));
  drawnow
  
end