clc
clear
close all

MIN_BOUND = 65;
MAX_BOUND = 120;

arduino = serialport(serialportlist, 115200);

sendAngle = @(a, b) writeline(arduino, sprintf('%s%d', b.AffectedObject.String, round(b.AffectedObject.Value)));

f = figure;

% A Control
a = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,50,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'A');
addlistener(a, 'Value', 'PostSet', sendAngle);

al1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,50,23,23],...
                           'String', a.Min);
al2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,50,23,23],...
                           'String', a.Max);
al3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,25,100,23],...
                           'String', a.String);

% B Control
b = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,200,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'B');
addlistener(b, 'Value', 'PostSet', sendAngle);

bl1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,200,23,23],...
                           'String', b.Min);
bl2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,200,23,23],...
                           'String', b.Max);
bl3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,175,100,23],...
                           'String', b.String);
                       
c = uicontrol('Parent', f, 'Style','slider', ...
                           'Position', [81,350,419,23],...
                           'Value', 0.5*(MIN_BOUND + MAX_BOUND), ...
                           'Min', MIN_BOUND, ...
                           'Max', MAX_BOUND, ...
                           'String', 'C');
addlistener(c, 'Value', 'PostSet', sendAngle);

cl1 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [50,350,23,23],...
                           'String', c.Min);
cl2 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [500,350,23,23],...
                           'String', c.Max);
cl3 = uicontrol('Parent',f,'Style', 'text', ...
                           'Position', [240,325,100,23],...
                           'String', c.String);